# CargoPulse AI — Feature Engineering

## Objective

Transform cleaned historical logistics data into meaningful,
validated features for:

1. Machine Learning
2. Shipment Simulation
3. Business Impact Analysis

## Input Datasets

- DataCo cleaned dataset
- Smart Logistics cleaned dataset

In [131]:
import pandas as pd
import numpy as np

In [2]:
dataco = pd.read_csv("../datasets/processed/dataco_cleaned.csv")

In [3]:
dataco_fe = dataco.copy()

In [4]:
print("DataCo shape:", dataco_fe.shape)

DataCo shape: (180519, 44)

In [5]:
print(dataco_fe.columns.tolist())

['type', 'days_for_shipping_real', 'days_for_shipment_scheduled', 'benefit_per_order', 'sales_per_customer', 'delivery_status', 'late_delivery_risk', 'category_id', 'category_name', 'customer_city', 'customer_country', 'customer_id', 'customer_segment', 'customer_state', 'customer_zipcode', 'department_id', 'department_name', 'latitude', 'longitude', 'market', 'order_city', 'order_country', 'order_customer_id', 'order_date_dateorders', 'order_id', 'order_item_cardprod_id', 'order_item_discount', 'order_item_discount_rate', 'order_item_id', 'order_item_product_price', 'order_item_profit_ratio', 'order_item_quantity', 'sales', 'order_item_total', 'order_profit_per_order', 'order_region', 'order_state', 'order_status', 'product_card_id', 'product_category_id', 'product_name', 'product_price', 'shipping_date_dateorders', 'shipping_mode']

In [6]:
print(dataco_fe.dtypes)

type                               str
days_for_shipping_real           int64
days_for_shipment_scheduled      int64
benefit_per_order              float64
sales_per_customer             float64
delivery_status                    str
late_delivery_risk               int64
category_id                      int64
category_name                      str
customer_city                      str
customer_country                   str
customer_id                      int64
customer_segment                   str
customer_state                     str
customer_zipcode               float64
department_id                    int64
department_name                    str
latitude                       float64
longitude                      float64
market                             str
order_city                         str
order_country                      str
order_customer_id                int64
order_date_dateorders              str
order_id                         int64
order_item_cardprod_id           int64
order_item_discount            float64
order_item_discount_rate       float64
order_item_id                    int64
order_item_product_price       float64
order_item_profit_ratio        float64
order_item_quantity              int64
sales                          float64
order_item_total               float64
order_profit_per_order         float64
order_region                       str
order_state                        str
order_status                       str
product_card_id                  int64
product_category_id              int64
product_name                       str
product_price                  float64
shipping_date_dateorders           str
shipping_mode                      str
dtype: object

In [7]:
display(dataco_fe.head())

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_profit_per_order,order_region,order_state,order_status,product_card_id,product_category_id,product_name,product_price,shipping_date_dateorders,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,91.250000,Southeast Asia,Java Occidental,COMPLETE,1360,73,Smart watch,327.75,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,-249.089996,South Asia,Rajastn,PENDING,1360,73,Smart watch,327.75,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,-247.779999,South Asia,Rajastn,CLOSED,1360,73,Smart watch,327.75,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,22.860001,Oceania,Queensland,COMPLETE,1360,73,Smart watch,327.75,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,134.210007,Oceania,Queensland,PENDING_PAYMENT,1360,73,Smart watch,327.75,1/15/2018 11:24,Standard Class

In [8]:
print("DataCo categorical columns:")

for col in [
    "type",
    "delivery_status",
    "shipping_mode",
    "market",
    "order_region",
    "customer_segment"
]:
    print(f"\n{col}:")
    print(dataco_fe[col].value_counts(dropna=False))

DataCo categorical columns:

type:
type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64

delivery_status:
delivery_status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

shipping_mode:
shipping_mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

market:
market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

order_region:
order_region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: count, dtype: int64

customer_segment:
customer_segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

In [9]:
print("DataCo target:")
print(dataco_fe["late_delivery_risk"].value_counts(dropna=False))

DataCo target:
late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [10]:
pd.crosstab(
    dataco_fe["delivery_status"],
    dataco_fe["late_delivery_risk"]
)

late_delivery_risk      0      1
delivery_status
Advance shipping    41592      0
Late delivery           0  98977
Shipping canceled    7754      0
Shipping on time    32196      0

Below code is just to check the data types missing value

In [11]:
print("DataCo date columns:")
print(dataco_fe[[
    "order_date_dateorders",
    "shipping_date_dateorders"
]].dtypes)

DataCo date columns:
order_date_dateorders       str
shipping_date_dateorders    str
dtype: object

In [12]:
print("\nMissing values:")
print(dataco_fe[[
    "order_date_dateorders",
    "shipping_date_dateorders"
]].isna().sum())

Missing values:
order_date_dateorders       0
shipping_date_dateorders    0
dtype: int64

In [13]:
print("\nDataCo date samples:")
print(dataco_fe[[
    "order_date_dateorders",
    "shipping_date_dateorders"
]].head(10))

DataCo date samples:
  order_date_dateorders shipping_date_dateorders
0       1/31/2018 22:56           2/3/2018 22:56
1       1/13/2018 12:27          1/18/2018 12:27
2       1/13/2018 12:06          1/17/2018 12:06
3       1/13/2018 11:45          1/16/2018 11:45
4       1/13/2018 11:24          1/15/2018 11:24
5       1/13/2018 11:03          1/19/2018 11:03
6       1/13/2018 10:42          1/15/2018 10:42
7       1/13/2018 10:21          1/15/2018 10:21
8       1/13/2018 10:00          1/16/2018 10:00
9        1/13/2018 9:39           1/15/2018 9:39

In [14]:
dataco_fe["order_date_dateorders"] = pd.to_datetime(
    dataco_fe["order_date_dateorders"]
)

dataco_fe["shipping_date_dateorders"] = pd.to_datetime(
    dataco_fe["shipping_date_dateorders"]
)

In [15]:
print("DataCo date columns:")
print(dataco_fe[[
    "order_date_dateorders",
    "shipping_date_dateorders"
]].dtypes)

DataCo date columns:
order_date_dateorders       datetime64[us]
shipping_date_dateorders    datetime64[us]
dtype: object

In [20]:
print("DataCo date types:")
print(
    dataco_fe[
        [
            "order_date_dateorders",
            "shipping_date_dateorders"
        ]
    ].dtypes
)

DataCo date types:
order_date_dateorders       datetime64[us]
shipping_date_dateorders    datetime64[us]
dtype: object

In [21]:
print(dataco_fe[
    [
        "order_date_dateorders",
        "shipping_date_dateorders"
    ]
].head())

  order_date_dateorders shipping_date_dateorders
0   2018-01-31 22:56:00      2018-02-03 22:56:00
1   2018-01-13 12:27:00      2018-01-18 12:27:00
2   2018-01-13 12:06:00      2018-01-17 12:06:00
3   2018-01-13 11:45:00      2018-01-16 11:45:00
4   2018-01-13 11:24:00      2018-01-15 11:24:00

==========================================Now we will create new columns or features ===============================================

==============================================feature 1(order_hour) ==================================================

In [16]:
dataco_fe["order_hour"] = (
    dataco_fe["order_date_dateorders"].dt.hour
)

In [147]:
# print(dataco_fe["order_hour"].value_counts().sort_index())

In [18]:
print(
    "DataCo valid hours:",
    dataco_fe["order_hour"].between(0, 23).all()
)

DataCo valid hours: True

In [19]:
print(dataco_fe[
    [
        "order_date_dateorders",
        "shipping_date_dateorders",
        "order_hour"
    ]
].head())

  order_date_dateorders shipping_date_dateorders  order_hour
0   2018-01-31 22:56:00      2018-02-03 22:56:00          22
1   2018-01-13 12:27:00      2018-01-18 12:27:00          12
2   2018-01-13 12:06:00      2018-01-17 12:06:00          12
3   2018-01-13 11:45:00      2018-01-16 11:45:00          11
4   2018-01-13 11:24:00      2018-01-15 11:24:00          11

In [20]:
print(
    "DataCo valid hours:",
    dataco_fe["order_hour"].between(0, 23).all()
)

DataCo valid hours: True

============================================FEATURE 2(order_day_of_week) ==================================================

In [21]:
dataco_fe["order_day_of_week"] = (
    dataco_fe["order_date_dateorders"].dt.dayofweek
)

In [22]:
print("DataCo day_of_week:")
print(
    dataco_fe["order_day_of_week"]
    .value_counts()
    .sort_index()
)

DataCo day_of_week:
order_day_of_week
0    25786
1    25622
2    25587
3    25752
4    25925
5    25901
6    25946
Name: count, dtype: int64

In [23]:
print(
    "DataCo valid day_of_week:",
    dataco_fe["order_day_of_week"]
    .between(0, 6)
    .all()
)

DataCo valid day_of_week: True

===============================================feature 3(order_month)=========================================================

In [24]:
dataco_fe["order_month"] =(
    dataco_fe["order_date_dateorders"].dt.month
)

In [25]:
print("dataco month")
print(dataco_fe["order_month"].value_counts().sort_index())

dataco month
order_month
1     17979
2     14529
3     15919
4     15435
5     15976
6     15139
7     15922
8     15912
9     15489
10    12955
11    12500
12    12764
Name: count, dtype: int64

In [26]:
print(
    "DataCo valid months:",
    dataco_fe["order_month"]
    .between(1, 12)
    .all()
)

DataCo valid months: True

=============================================Feature 4(is_weekend)===========================================================

In [27]:
dataco_fe["is_weekend"] = (
    dataco_fe["order_day_of_week"] >= 5
).astype(int)

In [28]:
print("DataCo is_weekend:")
print(
    dataco_fe["is_weekend"]
    .value_counts()
    .sort_index()
)

DataCo is_weekend:
is_weekend
0    128672
1     51847
Name: count, dtype: int64

In [29]:
print(
    "DataCo valid is_weekend:",
    dataco_fe["is_weekend"]
    .isin([0, 1])
    .all()
)

DataCo valid is_weekend: True

In [30]:
print(
    dataco_fe[
        [
            "order_date_dateorders",
            "order_day_of_week",
            "is_weekend"
        ]
    ].head(20)
)

   order_date_dateorders  order_day_of_week  is_weekend
0    2018-01-31 22:56:00                  2           0
1    2018-01-13 12:27:00                  5           1
2    2018-01-13 12:06:00                  5           1
3    2018-01-13 11:45:00                  5           1
4    2018-01-13 11:24:00                  5           1
5    2018-01-13 11:03:00                  5           1
6    2018-01-13 10:42:00                  5           1
7    2018-01-13 10:21:00                  5           1
8    2018-01-13 10:00:00                  5           1
9    2018-01-13 09:39:00                  5           1
10   2018-01-13 09:18:00                  5           1
11   2018-01-13 08:57:00                  5           1
12   2018-01-13 08:36:00                  5           1
13   2018-01-13 08:15:00                  5           1
14   2018-01-13 07:54:00                  5           1
15   2018-01-13 07:33:00                  5           1
16   2018-01-13 07:12:00                  5           1
17   2018-01-13 06:51:00                  5           1
18   2018-01-13 06:30:00                  5           1
19   2018-01-13 06:09:00                  5           1

In [31]:
##check if our logic is correct or not  
print(
    pd.crosstab(
        dataco_fe["order_day_of_week"],
        dataco_fe["is_weekend"]
    )
)

is_weekend             0      1
order_day_of_week
0                  25786      0
1                  25622      0
2                  25587      0
3                  25752      0
4                  25925      0
5                      0  25901
6                      0  25946

In [32]:
print("DataCo time features:")
print(
    dataco_fe[
        [
            "order_date_dateorders",
            "order_hour",
            "order_day_of_week",
            "order_month",
            "is_weekend"
        ]
    ].head(10)
)

print("\nDataCo validation:")

print(
    "Hour valid:",
    dataco_fe["order_hour"].between(0, 23).all()
)

print(
    "Day of week valid:",
    dataco_fe["order_day_of_week"].between(0, 6).all()
)

print(
    "Month valid:",
    dataco_fe["order_month"].between(1, 12).all()
)

print(
    "Weekend flag valid:",
    dataco_fe["is_weekend"].isin([0, 1]).all()
)

DataCo time features:
  order_date_dateorders  order_hour  order_day_of_week  order_month  \
0   2018-01-31 22:56:00          22                  2            1
1   2018-01-13 12:27:00          12                  5            1
2   2018-01-13 12:06:00          12                  5            1
3   2018-01-13 11:45:00          11                  5            1
4   2018-01-13 11:24:00          11                  5            1
5   2018-01-13 11:03:00          11                  5            1
6   2018-01-13 10:42:00          10                  5            1
7   2018-01-13 10:21:00          10                  5            1
8   2018-01-13 10:00:00          10                  5            1
9   2018-01-13 09:39:00           9                  5            1

   is_weekend
0           0
1           1
2           1
3           1
4           1
5           1
6           1
7           1
8           1
9           1

DataCo validation:
Hour valid: True
Day of week valid: True
Month valid: True
Weekend flag valid: True

==================================================Shipping Duration features=========================================================

In [33]:
print("Actual Shipping Duration")
print(dataco_fe["days_for_shipping_real"].describe())


print("\nScheduled shipping duration:")
print(dataco_fe["days_for_shipment_scheduled"].describe())

print("Actual shipping duration dtype:")
print(dataco_fe["days_for_shipping_real"].dtype)

print("\nScheduled shipping duration dtype:")
print(dataco_fe["days_for_shipment_scheduled"].dtype)

print("check missing value: ")
print(dataco_fe["days_for_shipping_real"].isna().sum())

print("\n Missing Scheduled shipping duration: ")
print(dataco_fe["days_for_shipment_scheduled"].isna().sum())

print(dataco[["days_for_shipping_real", "days_for_shipment_scheduled"]].head(20))

print(
    "Negative actual durations:",
    (dataco_fe["days_for_shipping_real"] < 0).sum()
)

print(
    "Negative scheduled durations:",
    (dataco_fe["days_for_shipment_scheduled"] < 0).sum()
)

Actual Shipping Duration
count    180519.000000
mean          3.497654
std           1.623722
min           0.000000
25%           2.000000
50%           3.000000
75%           5.000000
max           6.000000
Name: days_for_shipping_real, dtype: float64

Scheduled shipping duration:
count    180519.000000
mean          2.931847
std           1.374449
min           0.000000
25%           2.000000
50%           4.000000
75%           4.000000
max           4.000000
Name: days_for_shipment_scheduled, dtype: float64
Actual shipping duration dtype:
int64

Scheduled shipping duration dtype:
int64
check missing value:
0

 Missing Scheduled shipping duration:
0
    days_for_shipping_real  days_for_shipment_scheduled
0                        3                            4
1                        5                            4
2                        4                            4
3                        3                            4
4                        2                            4
5                        6                            4
6                        2                            1
7                        2                            1
8                        3                            2
9                        2                            1
10                       6                            2
11                       5                            2
12                       4                            2
13                       2                            1
14                       2                            1
15                       2                            1
16                       5                            2
17                       2                            1
18                       2                            1
19                       0                            0
Negative actual durations: 0
Negative scheduled durations: 0

In [34]:
#shipping delay features

dataco_fe["shipping_delay_days"] =(
    dataco_fe["days_for_shipping_real"]
    - dataco_fe["days_for_shipment_scheduled"]
)

##negative value means it arrive earlier and positive means it arrive late

In [36]:
print("=== Shipping Duration Validation ===")

print("\n1. Data Types:")
print(
    dataco_fe[
        [
            "days_for_shipping_real",
            "days_for_shipment_scheduled",
            "shipping_delay_days"
        ]
    ].dtypes
)

print("\n2. Missing Values:")
print(
    dataco_fe[
        [
            "days_for_shipping_real",
            "days_for_shipment_scheduled",
            "shipping_delay_days"
        ]
    ].isna().sum()
)

print("\n3. Sample Values:")
print(
    dataco_fe[
        [
            "days_for_shipping_real",
            "days_for_shipment_scheduled",
            "shipping_delay_days"
        ]
    ].head(10)
)

print("\n4. Feature Statistics:")
print(
    dataco_fe["shipping_delay_days"].describe()
)

print("\n5. Calculation Validation:")

validation_difference = (
    dataco_fe["days_for_shipping_real"]
    - dataco_fe["days_for_shipment_scheduled"]
)

print(
    "Calculation correct:",
    dataco_fe["shipping_delay_days"]
    .equals(validation_difference)
)

print("\n6. Business Interpretation:")

print(
    "Ahead of schedule:",
    (dataco_fe["shipping_delay_days"] < 0).sum()
)

print(
    "On schedule:",
    (dataco_fe["shipping_delay_days"] == 0).sum()
)

print(
    "Behind schedule:",
    (dataco_fe["shipping_delay_days"] > 0).sum()
)

=== Shipping Duration Validation ===

1. Data Types:
days_for_shipping_real         int64
days_for_shipment_scheduled    int64
shipping_delay_days            int64
dtype: object

2. Missing Values:
days_for_shipping_real         0
days_for_shipment_scheduled    0
shipping_delay_days            0
dtype: int64

3. Sample Values:
   days_for_shipping_real  days_for_shipment_scheduled  shipping_delay_days
0                       3                            4                   -1
1                       5                            4                    1
2                       4                            4                    0
3                       3                            4                   -1
4                       2                            4                   -2
5                       6                            4                    2
6                       2                            1                    1
7                       2                            1                    1
8                       3                            2                    1
9                       2                            1                    1

4. Feature Statistics:
count    180519.000000
mean          0.565807
std           1.490966
min          -2.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: shipping_delay_days, dtype: float64

5. Calculation Validation:
Calculation correct: True

6. Business Interpretation:
Ahead of schedule: 43366
On schedule: 33753
Behind schedule: 103400

In [37]:
print(dataco_fe.groupby("late_delivery_risk")["shipping_delay_days"].describe())

                      count      mean       std  min  25%  50%  75%  max
late_delivery_risk
0                   81542.0 -0.711584  0.999927 -2.0 -2.0 -1.0  0.0  4.0
1                   98977.0  1.618184  0.882527  1.0  1.0  1.0  2.0  4.0

In [38]:
print(
    dataco_fe[
        [
            "days_for_shipping_real",
            "days_for_shipment_scheduled",
            "shipping_delay_days"
        ]
    ].head(10)
)

print(
    "DataCo feature count:",
    len(dataco_fe.columns)
)

   days_for_shipping_real  days_for_shipment_scheduled  shipping_delay_days
0                       3                            4                   -1
1                       5                            4                    1
2                       4                            4                    0
3                       3                            4                   -1
4                       2                            4                   -2
5                       6                            4                    2
6                       2                            1                    1
7                       2                            1                    1
8                       3                            2                    1
9                       2                            1                    1
DataCo feature count: 49

In [120]:
# dataco_fe.columns

In [ ]:
####################################Optional Validation of Calender_shipping_duration(it is not created as a new features)======================================

In [109]:
calender_shipping_duration=(
    dataco_fe["shipping_date_dateorders"] - dataco_fe["order_date_dateorders"]
).dt.total_seconds() / (24 * 60 * 60)

In [110]:
print(calender_shipping_duration.head(10))

0    3.0
1    5.0
2    4.0
3    3.0
4    2.0
5    6.0
6    2.0
7    2.0
8    3.0
9    2.0
dtype: float64

In [111]:
print(dataco_fe[
    [
        "days_for_shipping_real", "days_for_shipment_scheduled"
    ]
].head(10))

print("\n calender duration: ")
print(calender_shipping_duration.head(10))

   days_for_shipping_real  days_for_shipment_scheduled
0                       3                            4
1                       5                            4
2                       4                            4
3                       3                            4
4                       2                            4
5                       6                            4
6                       2                            1
7                       2                            1
8                       3                            2
9                       2                            1

 calender duration:
0    3.0
1    5.0
2    4.0
3    3.0
4    2.0
5    6.0
6    2.0
7    2.0
8    3.0
9    2.0
dtype: float64

In [113]:
duration_difference = (
    calender_shipping_duration
    - dataco_fe["days_for_shipping_real"]
)

print(
    duration_difference.describe()
)

count    180519.000000
mean          0.001172
std           0.116118
min          -0.500000
25%           0.000000
50%           0.000000
75%           0.000000
max           0.500000
dtype: float64

In [114]:
print(
    "Rows where calendar duration differs:",
    (duration_difference != 0).sum()
)

Rows where calendar duration differs: 9737

In [ ]:
del calender_shipping_duration
del duration_difference

############################################################################################################################################

========================================Inspect DataCo Location Features===================================================================

In [98]:
print("=== DataCo Location Feature Data Types ===")

print(
    dataco_fe[
        [
            "latitude",
            "longitude",
            "market",
            "order_region",
            "order_country",
            "order_state",
            "customer_country",
            "customer_state"
        ]
    ].dtypes
)

print("\n=== DataCo Location Missing Values ===")

print(
    dataco_fe[
        [
            "latitude",
            "longitude",
            "market",
            "order_region",
            "order_country",
            "order_state",
            "customer_country",
            "customer_state"
        ]
    ].isna().sum()
)

print("\n=== DataCo Coordinate Statistics ===")

print(
    dataco_fe[
        [
            "latitude",
            "longitude"
        ]
    ].describe()
)

print("\n=== DataCo Coordinate Validation ===")

print(
    "Invalid latitude:",
    (
        (dataco_fe["latitude"] < -90) |
        (dataco_fe["latitude"] > 90)
    ).sum()
)

print(
    "Invalid longitude:",
    (
        (dataco_fe["longitude"] < -180) |
        (dataco_fe["longitude"] > 180)
    ).sum()
)

print("\n=== DataCo Market ===")

print(
    dataco_fe["market"]
    .value_counts(dropna=False)
)

print("\n=== DataCo Order Region ===")

print(
    dataco_fe["order_region"]
    .value_counts(dropna=False)
)

print("\n=== DataCo Order Country ===")

print(
    dataco_fe["order_country"]
    .nunique()
)

print("\nUnique order countries:")
print(
    dataco_fe["order_country"]
    .unique()
)

print("\n=== DataCo Coordinate Uniqueness ===")

print(
    "Unique coordinate pairs:",
    dataco_fe[
        ["latitude", "longitude"]
    ].drop_duplicates().shape[0]
)

print(
    "Total rows:",
    len(dataco_fe)
)

=== DataCo Location Feature Data Types ===
latitude            float64
longitude           float64
market                  str
order_region            str
order_country           str
order_state             str
customer_country        str
customer_state          str
dtype: object

=== DataCo Location Missing Values ===
latitude            0
longitude           0
market              0
order_region        0
order_country       0
order_state         0
customer_country    0
customer_state      0
dtype: int64

=== DataCo Coordinate Statistics ===
            latitude      longitude
count  180519.000000  180519.000000
mean       29.719955     -84.915675
std         9.813646      21.433241
min       -33.937553    -158.025986
25%        18.265432     -98.446312
50%        33.144863     -76.847908
75%        39.279617     -66.370583
max        48.781933     115.263077

=== DataCo Coordinate Validation ===
Invalid latitude: 0
Invalid longitude: 0

=== DataCo Market ===
market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

=== DataCo Order Region ===
order_region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: count, dtype: int64

=== DataCo Order Country ===
164

Unique order countries:
<StringArray>
[         'Indonesia',              'India',          'Australia',
              'China',               'Japn',      'Corea del Sur',
           'Singapur',             'Turqua',           'Mongolia',
     'Estados Unidos',
 ...
          'Eslovenia', 'Repblica de Gambia',           'Botsuana',
            'Armenia',  'Guinea Ecuatorial',             'Kuwait',
               'Butn',               'Chad',             'Serbia',
   'Shara Occidental']
Length: 164, dtype: str

=== DataCo Coordinate Uniqueness ===
Unique coordinate pairs: 11835
Total rows: 180519

In [100]:
dataco_location_features = [
    "latitude",
    "longitude",
    "market",
    "order_region",
    "order_country",
    "order_state",
    "customer_country",
    "customer_state"
]

print("DataCo location features:")
print(dataco_location_features)

DataCo location features:
['latitude', 'longitude', 'market', 'order_region', 'order_country', 'order_state', 'customer_country', 'customer_state']

In [101]:
missing_dataco_location = [
    col
    for col in dataco_location_features
    if col not in dataco_fe.columns
]
print("Missing DataCo location features:")
print(missing_dataco_location)

Missing DataCo location features:
[]

=============================================Historical performance features==================================================================
see i am evaluating and checking the dataset to create new features if it is suitable

In [109]:
historical_group_features = [
    "shipping_mode",
    "market",
    "order_region",
    "customer_segment"
]

for col in historical_group_features:

    print(f"\n=== {col} ===")

    print(
        dataco_fe[col]
        .value_counts()
    )

print("\n\n")

print(
dataco_fe.groupby("shipping_mode")[
    "late_delivery_risk"
].mean()
)
print("\n\n")
print(
    dataco_fe.groupby("market")[
        "late_delivery_risk"
    ].mean()
)
print("\n\n")
print(
    dataco_fe.groupby("order_region")[
        "late_delivery_risk"
    ].mean()
)

=== shipping_mode ===
shipping_mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

=== market ===
market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

=== order_region ===
order_region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: count, dtype: int64

=== customer_segment ===
customer_segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64



shipping_mode
First Class       0.953225
Same Day          0.457430
Second Class      0.766328
Standard Class    0.380717
Name: late_delivery_risk, dtype: float64



market
Africa          0.545893
Europe          0.552078
LATAM           0.543552
Pacific Asia    0.550460
USCA            0.548006
Name: late_delivery_risk, dtype: float64



order_region
Canada             0.488008
Caribbean          0.530777
Central Africa     0.579606
Central America    0.547546
Central Asia       0.553345
East Africa        0.559395
East of USA        0.556616
Eastern Asia       0.543269
Eastern Europe     0.556633
North Africa       0.545173
Northern Europe    0.540441
Oceania            0.540205
South America      0.543087
South Asia         0.562670
South of  USA      0.557726
Southeast Asia     0.555299
Southern Africa    0.533276
Southern Europe    0.543845
US Center          0.552404
West Africa        0.528409
West Asia          0.552837
West of USA        0.539597
Western Europe     0.558486
Name: late_delivery_risk, dtype: float64

In [108]:
# Check Date Ordering
print("Order date range:")

print(
    dataco_fe["order_date_dateorders"].min()
)

print(
    dataco_fe["order_date_dateorders"].max()
)

print("\nIs order date sorted?")

print(
    dataco_fe["order_date_dateorders"]
    .is_monotonic_increasing
)

Order date range:
2015-01-01 00:00:00
2018-01-31 23:38:00

Is order date sorted?
False

In [125]:
# ============================================================
# Step 11 — Historical Performance Feature
# Feature: shipping_mode_delay_rate
# ============================================================

# Create a working copy
dataco_history = dataco_fe.copy()


# ------------------------------------------------------------
# 1. Convert date column to datetime
# ------------------------------------------------------------

dataco_history["order_date_dateorders"] = pd.to_datetime(
    dataco_history["order_date_dateorders"]
)


# ------------------------------------------------------------
# 2. Sort data chronologically
# ------------------------------------------------------------

dataco_history = (
    dataco_history
    .sort_values("order_date_dateorders")
    .reset_index(drop=True)
)


print(
    "Is date sorted:",
    dataco_history["order_date_dateorders"].is_monotonic_increasing
)


# ------------------------------------------------------------
# 3. Calculate statistics for each
#    shipping mode at each timestamp
# ------------------------------------------------------------

mode_time_stats = (
    dataco_history
    .groupby(
        [
            "shipping_mode",
            "order_date_dateorders"
        ]
    )["late_delivery_risk"]
    .agg(
        delay_sum="sum",
        shipment_count="count"
    )
    .reset_index()
)


# ------------------------------------------------------------
# 4. Calculate cumulative historical values
# ------------------------------------------------------------

mode_time_stats["cumulative_delay_sum"] = (
    mode_time_stats
    .groupby("shipping_mode")["delay_sum"]
    .cumsum()
)

mode_time_stats["cumulative_shipment_count"] = (
    mode_time_stats
    .groupby("shipping_mode")["shipment_count"]
    .cumsum()
)


# ------------------------------------------------------------
# 5. Shift by one timestamp
#    This prevents the current timestamp from being used.
# ------------------------------------------------------------

mode_time_stats["previous_delay_sum"] = (
    mode_time_stats
    .groupby("shipping_mode")["cumulative_delay_sum"]
    .shift(1)
)

mode_time_stats["previous_shipment_count"] = (
    mode_time_stats
    .groupby("shipping_mode")["cumulative_shipment_count"]
    .shift(1)
)


# ------------------------------------------------------------
# 6. Create the final feature
# ------------------------------------------------------------

mode_time_stats["shipping_mode_delay_rate"] = (
    mode_time_stats["previous_delay_sum"]
    /
    mode_time_stats["previous_shipment_count"]
)


# ------------------------------------------------------------
# 7. Merge the feature back into the dataset
# ------------------------------------------------------------

dataco_history = dataco_history.merge(
    mode_time_stats[
        [
            "shipping_mode",
            "order_date_dateorders",
            "shipping_mode_delay_rate"
        ]
    ],
    on=[
        "shipping_mode",
        "order_date_dateorders"
    ],
    how="left"
)


# ============================================================
# VALIDATION
# ============================================================

print("\n=== Shipping Mode Delay Rate ===")

print(
    dataco_history[
        [
            "order_date_dateorders",
            "shipping_mode",
            "late_delivery_risk",
            "shipping_mode_delay_rate"
        ]
    ].head(20)
)


# ------------------------------------------------------------
# Check same timestamp consistency
# ------------------------------------------------------------

same_timestamp_variation = (
    dataco_history
    .groupby(
        [
            "shipping_mode",
            "order_date_dateorders"
        ]
    )["shipping_mode_delay_rate"]
    .nunique()
)


print(
    "\nMaximum different historical rates "
    "within the same timestamp:",
    same_timestamp_variation.max()
)


# ------------------------------------------------------------
# Check missing values
# ------------------------------------------------------------

print(
    "\nMissing shipping mode delay rates:",
    dataco_history[
        "shipping_mode_delay_rate"
    ].isna().sum()
)

Is date sorted: True

=== Shipping Mode Delay Rate ===
   order_date_dateorders   shipping_mode  late_delivery_risk  \
0    2015-01-01 00:00:00  Standard Class                   0
1    2015-01-01 00:21:00  Standard Class                   0
2    2015-01-01 00:21:00  Standard Class                   0
3    2015-01-01 00:21:00  Standard Class                   0
4    2015-01-01 01:03:00  Standard Class                   1
5    2015-01-01 01:03:00  Standard Class                   1
6    2015-01-01 01:03:00  Standard Class                   1
7    2015-01-01 01:03:00  Standard Class                   1
8    2015-01-01 01:24:00  Standard Class                   1
9    2015-01-01 01:24:00  Standard Class                   1
10   2015-01-01 01:24:00  Standard Class                   1
11   2015-01-01 01:24:00  Standard Class                   1
12   2015-01-01 01:24:00  Standard Class                   1
13   2015-01-01 02:06:00    Second Class                   1
14   2015-01-01 02:06:00    Second Class                   1
15   2015-01-01 02:06:00    Second Class                   1
16   2015-01-01 02:27:00  Standard Class                   0
17   2015-01-01 02:27:00  Standard Class                   0
18   2015-01-01 02:27:00  Standard Class                   0
19   2015-01-01 02:27:00  Standard Class                   0

    shipping_mode_delay_rate
0                        NaN
1                   0.000000
2                   0.000000
3                   0.000000
4                   0.000000
5                   0.000000
6                   0.000000
7                   0.000000
8                   0.500000
9                   0.500000
10                  0.500000
11                  0.500000
12                  0.500000
13                       NaN
14                       NaN
15                       NaN
16                  0.692308
17                  0.692308
18                  0.692308
19                  0.692308

Maximum different historical rates within the same timestamp: 1

Missing shipping mode delay rates: 9

In [126]:
print(
    dataco_history[
        "shipping_mode_delay_rate"
    ].describe()
)

count    180510.000000
mean          0.548866
std           0.229045
min           0.000000
25%           0.380749
50%           0.381800
75%           0.769083
max           1.000000
Name: shipping_mode_delay_rate, dtype: float64

In [129]:
print(
    "Missing values:",
    dataco_history[
        "shipping_mode_delay_rate"
    ].isna().sum()
)

Missing values: 9

In [132]:
print(
    "Infinite values:",
    np.isinf(
        dataco_history[
            "shipping_mode_delay_rate"
        ]
    ).sum()
)

Infinite values: 0

In [156]:
dataco_fe = dataco_history.copy()

In [157]:
print(
    "shipping_mode_delay_rate"
    in dataco_fe.columns
)

True

In [158]:
print(
    dataco_fe[
        [
            "shipping_mode",
            "shipping_mode_delay_rate"
        ]
    ].head(10)
)

    shipping_mode  shipping_mode_delay_rate
0  Standard Class                       NaN
1  Standard Class                       0.0
2  Standard Class                       0.0
3  Standard Class                       0.0
4  Standard Class                       0.0
5  Standard Class                       0.0
6  Standard Class                       0.0
7  Standard Class                       0.0
8  Standard Class                       0.5
9  Standard Class                       0.5

==================================================Inspect Business Features=====================================================================

In [133]:
print("=== Business Feature Data Types ===")

business_features = [
    "benefit_per_order",
    "sales_per_customer",
    "order_item_product_price",
    "order_item_quantity",
    "sales",
    "order_item_total",
    "order_profit_per_order",
    "order_item_profit_ratio"
]

print(
    dataco_fe[business_features].dtypes
)

print("\n=== Business Feature Missing Values ===")

print(
    dataco_fe[business_features].isna().sum()
)

print("\n=== Business Feature Statistics ===")

print(
    dataco_fe[business_features].describe()
)

print("\n=== Business Feature Samples ===")

print(
    dataco_fe[business_features].head(10)
)

=== Business Feature Data Types ===
benefit_per_order           float64
sales_per_customer          float64
order_item_product_price    float64
order_item_quantity           int64
sales                       float64
order_item_total            float64
order_profit_per_order      float64
order_item_profit_ratio     float64
dtype: object

=== Business Feature Missing Values ===
benefit_per_order           0
sales_per_customer          0
order_item_product_price    0
order_item_quantity         0
sales                       0
order_item_total            0
order_profit_per_order      0
order_item_profit_ratio     0
dtype: int64

=== Business Feature Statistics ===
       benefit_per_order  sales_per_customer  order_item_product_price  \
count      180519.000000       180519.000000             180519.000000
mean           21.974989          183.107609                141.232550
std           104.433526          120.043670                139.732492
min         -4274.979980            7.490000                  9.990000
25%             7.000000          104.379997                 50.000000
50%            31.520000          163.990005                 59.990002
75%            64.800003          247.399994                199.990005
max           911.799988         1939.989990               1999.989990

       order_item_quantity          sales  order_item_total  \
count        180519.000000  180519.000000     180519.000000
mean              2.127638     203.772096        183.107609
std               1.453451     132.273077        120.043670
min               1.000000       9.990000          7.490000
25%               1.000000     119.980003        104.379997
50%               1.000000     199.919998        163.990005
75%               3.000000     299.950012        247.399994
max               5.000000    1999.989990       1939.989990

       order_profit_per_order  order_item_profit_ratio
count           180519.000000            180519.000000
mean                21.974989                 0.120647
std                104.433526                 0.466796
min              -4274.979980                -2.750000
25%                  7.000000                 0.080000
50%                 31.520000                 0.270000
75%                 64.800003                 0.360000
max                911.799988                 0.500000

=== Business Feature Samples ===
   benefit_per_order  sales_per_customer  order_item_product_price  \
0          91.250000          314.640015                    327.75
1        -249.089996          311.359985                    327.75
2        -247.779999          309.720001                    327.75
3          22.860001          304.809998                    327.75
4         134.210007          298.250000                    327.75
5          18.580000          294.980011                    327.75
6          95.180000          288.420013                    327.75
7          68.430000          285.140015                    327.75
8         133.720001          278.589996                    327.75
9         132.149994          275.309998                    327.75

   order_item_quantity   sales  order_item_total  order_profit_per_order  \
0                    1  327.75        314.640015               91.250000
1                    1  327.75        311.359985             -249.089996
2                    1  327.75        309.720001             -247.779999
3                    1  327.75        304.809998               22.860001
4                    1  327.75        298.250000              134.210007
5                    1  327.75        294.980011               18.580000
6                    1  327.75        288.420013               95.180000
7                    1  327.75        285.140015               68.430000
8                    1  327.75        278.589996              133.720001
9                    1  327.75        275.309998              132.149994

   order_item_profit_ratio
0                     0.29
1                    -0.80
2                    -0.80
3                     0.08
4                     0.45
5                     0.06
6                     0.33
7                     0.24
8                     0.48
9                     0.48

In [134]:
business_impact_features = [
    "sales",
    "order_profit_per_order",
    "order_item_profit_ratio",
    "order_item_quantity"
]

print("Business impact features:")

print(business_impact_features)

Business impact features:
['sales', 'order_profit_per_order', 'order_item_profit_ratio', 'order_item_quantity']

In [135]:
missing_business_features = [
    col
    for col in business_impact_features
    if col not in dataco_fe.columns
]

print("\nMissing business features:")
print(missing_business_features)

Missing business features:
[]

In [136]:
print("\n=== Business Impact Feature Validation ===")

print(
    dataco_fe[
        business_impact_features
    ].isna().sum()
)

print("\nStatistics:")

print(
    dataco_fe[
        business_impact_features
    ].describe()
)

=== Business Impact Feature Validation ===
sales                      0
order_profit_per_order     0
order_item_profit_ratio    0
order_item_quantity        0
dtype: int64

Statistics:
               sales  order_profit_per_order  order_item_profit_ratio  \
count  180519.000000           180519.000000            180519.000000
mean      203.772096               21.974989                 0.120647
std       132.273077              104.433526                 0.466796
min         9.990000            -4274.979980                -2.750000
25%       119.980003                7.000000                 0.080000
50%       199.919998               31.520000                 0.270000
75%       299.950012               64.800003                 0.360000
max      1999.989990              911.799988                 0.500000

       order_item_quantity
count        180519.000000
mean              2.127638
std               1.453451
min               1.000000
25%               1.000000
50%               1.000000
75%               3.000000
max               5.000000

=============================================Inspect Late_delivery_risk=======================================================

In [145]:
print("=== Target Validation ===")

print("\nData Type:")
print(dataco_fe["late_delivery_risk"].dtype)

print("\nUnique Values:")
print(dataco_fe["late_delivery_risk"].unique())

print("\nValue Counts:")
print(
    dataco_fe["late_delivery_risk"].value_counts()
)

print("\nValue Percentages:")
print(
    dataco_fe["late_delivery_risk"]
    .value_counts(normalize=True)
    * 100
)

print("\nMissing Values:")
print(
    dataco_fe["late_delivery_risk"].isna().sum()
)

=== Target Validation ===

Data Type:
int64

Unique Values:
[0 1]

Value Counts:
late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

Value Percentages:
late_delivery_risk
1    54.829132
0    45.170868
Name: proportion, dtype: float64

Missing Values:
0

In [146]:
leakage_candidates = [
    "delivery_status",
    "order_status",
    "days_for_shipping_real",
    "shipping_delay_days"
]

print("=== Potential Leakage Features ===")

for col in leakage_candidates:

    print(f"\n{col}")

    print(
        dataco_fe[
            [col, "late_delivery_risk"]
        ].head()
    )

=== Potential Leakage Features ===

delivery_status
    delivery_status  late_delivery_risk
0  Advance shipping                   0
1     Late delivery                   1
2  Shipping on time                   0
3  Advance shipping                   0
4  Advance shipping                   0

order_status
      order_status  late_delivery_risk
0         COMPLETE                   0
1          PENDING                   1
2           CLOSED                   0
3         COMPLETE                   0
4  PENDING_PAYMENT                   0

days_for_shipping_real
   days_for_shipping_real  late_delivery_risk
0                       3                   0
1                       5                   1
2                       4                   0
3                       3                   0
4                       2                   0

shipping_delay_days
   shipping_delay_days  late_delivery_risk
0                   -1                   0
1                    1                   1
2                    0                   0
3                   -1                   0
4                   -2                   0

===============================================Final Feature Classification=============================================================

In [148]:
dataco_ml_features = [
    # Time
    "order_hour",
    "order_day_of_week",
    "order_month",
    "is_weekend",

    # Shipment / business context
    "days_for_shipment_scheduled",
    "shipping_mode",

    # Location
    "market",
    "order_region",

    # Customer context
    "customer_segment",

    # Business
    "sales",
    "order_profit_per_order",
    "order_item_profit_ratio",
    "order_item_quantity",

    # Historical performance
    "shipping_mode_delay_rate"
]

print("DataCo ML Features:")
print(dataco_ml_features)

DataCo ML Features:
['order_hour', 'order_day_of_week', 'order_month', 'is_weekend', 'days_for_shipment_scheduled', 'shipping_mode', 'market', 'order_region', 'customer_segment', 'sales', 'order_profit_per_order', 'order_item_profit_ratio', 'order_item_quantity', 'shipping_mode_delay_rate']

In [149]:
dataco_target = "late_delivery_risk"

print("Target:")
print(dataco_target)

Target:
late_delivery_risk

In [150]:
core_simulation_features = [
    "traffic_status",
    "temperature",
    "humidity",
    "waiting_time",
    "asset_utilization"
]

print("Simulation Features:")
print(core_simulation_features)

Simulation Features:
['traffic_status', 'temperature', 'humidity', 'waiting_time', 'asset_utilization']

In [151]:
business_impact_features = [
    "sales",
    "order_profit_per_order",
    "order_item_profit_ratio",
    "order_item_quantity"
]

print("Business Features:")
print(business_impact_features)

Business Features:
['sales', 'order_profit_per_order', 'order_item_profit_ratio', 'order_item_quantity']

In [152]:
leakage_features = [
    "delivery_status",
    "order_status",
    "days_for_shipping_real",
    "shipping_delay_days"
]

print("Excluded Leakage / Future-Unavailable Features:")
print(leakage_features)

Excluded Leakage / Future-Unavailable Features:
['delivery_status', 'order_status', 'days_for_shipping_real', 'shipping_delay_days']

In [159]:
missing_ml_features = [
    col
    for col in dataco_ml_features
    if col not in dataco_fe.columns
]

print("Missing ML features:")
print(missing_ml_features)

print(
    "\nTarget accidentally included:",
    dataco_target in dataco_ml_features
)

Missing ML features:
[]

Target accidentally included: False

In [155]:
leakage_in_ml = [
    col
    for col in leakage_features
    if col in dataco_ml_features
]

print(
    "\nLeakage features inside ML features:"
)

print(leakage_in_ml)

Leakage features inside ML features:
[]

Final DataFrame Inspection

In [161]:
print("DataCo final feature-engineered shape:")
print(dataco_fe.shape)

print("\nDataCo columns:")
print(dataco_fe.columns.tolist())

DataCo final feature-engineered shape:
(180519, 50)

DataCo columns:
['type', 'days_for_shipping_real', 'days_for_shipment_scheduled', 'benefit_per_order', 'sales_per_customer', 'delivery_status', 'late_delivery_risk', 'category_id', 'category_name', 'customer_city', 'customer_country', 'customer_id', 'customer_segment', 'customer_state', 'customer_zipcode', 'department_id', 'department_name', 'latitude', 'longitude', 'market', 'order_city', 'order_country', 'order_customer_id', 'order_date_dateorders', 'order_id', 'order_item_cardprod_id', 'order_item_discount', 'order_item_discount_rate', 'order_item_id', 'order_item_product_price', 'order_item_profit_ratio', 'order_item_quantity', 'sales', 'order_item_total', 'order_profit_per_order', 'order_region', 'order_state', 'order_status', 'product_card_id', 'product_category_id', 'product_name', 'product_price', 'shipping_date_dateorders', 'shipping_mode', 'order_hour', 'order_day_of_week', 'order_month', 'is_weekend', 'shipping_delay_days', 'shipping_mode_delay_rate']

In [164]:
print("=== DataCo Missing Values ===")

print(
    dataco_fe.isna().sum()[
        dataco_fe.isna().sum() > 0
    ]
)

=== DataCo Missing Values ===
customer_zipcode            3
shipping_mode_delay_rate    9
dtype: int64

In [165]:
print(
    "DataCo duplicate rows:",
    dataco_fe.duplicated().sum()
)

DataCo duplicate rows: 0

"""""""""""""""""""""""""""""""""""Save the final processed Dataset"""""""""""""""""""""""""""""""""""""""""""""""""""""""""

In [167]:
dataco_fe.to_csv(
    "../datasets/processed/dataco_features.csv",
    index=False
)

In [168]:
import os

print(
    os.path.exists(
        "../datasets/processed/dataco_features.csv"
    )
)

True

=================================================Smart Logistics Dataset===============================================================

In [39]:
smart = pd.read_csv("../datasets/processed/smart_logistics_cleaned.csv")

In [40]:
smart_fe = smart.copy()

In [ ]:
# smart_fe.shape
# smart_fe.head()

,timestamp,asset_id,latitude,longitude,inventory_level,shipment_status,temperature,humidity,traffic_status,waiting_time,user_transaction_amount,user_purchase_frequency,logistics_delay_reason,asset_utilization,demand_forecast,logistics_delay,hour,day_of_week,month,is_weekend
0,2024-03-20 00:11:14,Truck_7,-65.7383,11.2497,390,Delayed,27.0,67.8,Detour,38,320,4,NaN,60.1,285,1,0,2,3,0
1,2024-10-30 07:53:51,Truck_6,22.2748,-131.7086,491,In Transit,22.5,54.3,Heavy,16,439,7,Weather,80.9,174,1,7,2,10,0
2,2024-07-29 18:42:48,Truck_10,54.9232,79.5455,190,In Transit,25.2,62.2,Detour,34,355,3,NaN,99.2,260,0,18,0,7,0
3,2024-10-28 00:50:54,Truck_9,42.3900,-1.4788,330,Delivered,25.4,52.3,Heavy,37,227,5,Traffic,97.4,160,1,0,0,10,0
4,2024-09-27 15:52:58,Truck_7,-65.8477,47.9468,480,Delayed,20.5,57.2,Clear,56,197,6,NaN,71.6,270,1,15,4,9,0

In [42]:
print(smart_fe.columns.tolist())

['timestamp', 'asset_id', 'latitude', 'longitude', 'inventory_level', 'shipment_status', 'temperature', 'humidity', 'traffic_status', 'waiting_time', 'user_transaction_amount', 'user_purchase_frequency', 'logistics_delay_reason', 'asset_utilization', 'demand_forecast', 'logistics_delay']

In [43]:
print(smart_fe.dtypes)

timestamp                      str
asset_id                       str
latitude                   float64
longitude                  float64
inventory_level              int64
shipment_status                str
temperature                float64
humidity                   float64
traffic_status                 str
waiting_time                 int64
user_transaction_amount      int64
user_purchase_frequency      int64
logistics_delay_reason         str
asset_utilization          float64
demand_forecast              int64
logistics_delay              int64
dtype: object

In [45]:
# display(smart_fe.head())

In [46]:
print("Smart Logistics categorical columns:")

for col in [
    "shipment_status",
    "traffic_status",
    "logistics_delay_reason"
]:
    print(f"\n{col}:")
    print(smart_fe[col].value_counts(dropna=False))

Smart Logistics categorical columns:

shipment_status:
shipment_status
Delayed       350
Delivered     338
In Transit    312
Name: count, dtype: int64

traffic_status:
traffic_status
Detour    345
Clear     328
Heavy     327
Name: count, dtype: int64

logistics_delay_reason:
logistics_delay_reason
Weather               267
NaN                   263
Traffic               236
Mechanical Failure    234
Name: count, dtype: int64

In [47]:
print("\nSmart Logistics target:")
print(smart_fe["logistics_delay"].value_counts(dropna=False))

Smart Logistics target:
logistics_delay
1    566
0    434
Name: count, dtype: int64

In [48]:
pd.crosstab(
    smart_fe["shipment_status"],
    smart_fe["logistics_delay"]
)

logistics_delay    0    1
shipment_status
Delayed            0  350
Delivered        220  118
In Transit       214   98

In [49]:
pd.crosstab(
    smart_fe["logistics_delay_reason"],
    smart_fe["logistics_delay"],
    dropna=False
)

logistics_delay           0    1
logistics_delay_reason
Mechanical Failure      101  133
Traffic                 101  135
Weather                 116  151
NaN                     116  147

Below code is just to check the datatype

In [50]:
print("Smart Logistics timestamp dtype: ")
print(smart_fe["timestamp"].dtype)

Smart Logistics timestamp dtype:
str

In [51]:
print("\n Missing timestamps: ")
print(smart_fe["timestamp"].isna().sum())

 Missing timestamps:
0

In [52]:
print("\n Timestamp samples: ")
print(smart_fe["timestamp"].head(10))

 Timestamp samples:
0    2024-03-20 00:11:14
1    2024-10-30 07:53:51
2    2024-07-29 18:42:48
3    2024-10-28 00:50:54
4    2024-09-27 15:52:58
5    2024-09-17 06:02:15
6    2024-02-05 08:38:56
7    2024-09-28 09:08:23
8    2024-01-18 08:27:04
9    2024-11-09 00:48:26
Name: timestamp, dtype: str

In [53]:
print("\n Timestamp range: ")
print("Smart: ", smart_fe["timestamp"].min())
print("End: ", smart_fe["timestamp"].max())

 Timestamp range:
Smart:  2024-01-01 11:37:57
End:  2024-12-30 20:21:58

In [54]:
smart_fe["timestamp"] = pd.to_datetime(
    smart_fe["timestamp"]
)

In [55]:
print("\nSmart Logistics timestamp type:")
print(smart_fe["timestamp"].dtype)

Smart Logistics timestamp type:
datetime64[us]

In [56]:
print("\nSmart Logistics missing timestamps after conversion:")

print(
    smart_fe["timestamp"].isna().sum()
)

Smart Logistics missing timestamps after conversion:
0

In [57]:
print(smart_fe["timestamp"].head())

0   2024-03-20 00:11:14
1   2024-10-30 07:53:51
2   2024-07-29 18:42:48
3   2024-10-28 00:50:54
4   2024-09-27 15:52:58
Name: timestamp, dtype: datetime64[us]

=========================================Now we will create new features based on our needs ==========================================

In [ ]:
# ==========================================feature 1(Hour)======================================================

In [58]:
smart_fe["hour"] = (
    smart_fe["timestamp"].dt.hour
)

In [63]:
# print(smart_fe["hour"].value_counts().sort_index())

In [59]:
print(smart_fe[
    [
        "timestamp",
        "hour"
    ]
].head())

            timestamp  hour
0 2024-03-20 00:11:14     0
1 2024-10-30 07:53:51     7
2 2024-07-29 18:42:48    18
3 2024-10-28 00:50:54     0
4 2024-09-27 15:52:58    15

==========================================feature 2(day_of_week)============================================================

In [60]:
smart_fe["day_of_week"]=(
    smart_fe["timestamp"].dt.dayofweek
)

In [61]:
print("\nSmart Logistics day_of_week:")
print(
    smart_fe["day_of_week"]
    .value_counts()
    .sort_index()
)

Smart Logistics day_of_week:
day_of_week
0    153
1    140
2    158
3    135
4    147
5    139
6    128
Name: count, dtype: int64

In [62]:
print(
    "Smart Logistics valid day_of_week:",
    smart_fe["day_of_week"]
    .between(0, 6)
    .all()
)

Smart Logistics valid day_of_week: True

===============================================feature 3(month)=========================================================

In [63]:
smart_fe["month"] = (
    smart_fe["timestamp"].dt.month
)

In [64]:
print("\nSmart Logistics months:")
print(
    smart_fe["month"]
    .value_counts()
    .sort_index()
)

Smart Logistics months:
month
1     92
2     77
3     94
4     86
5     74
6     77
7     86
8     77
9     83
10    83
11    82
12    89
Name: count, dtype: int64

In [65]:
print(
    "Smart Logistics valid months:",
    smart_fe["month"]
    .between(1, 12)
    .all()
)

Smart Logistics valid months: True

=============================================Feature 4(is_weekend)===========================================================

In [66]:
smart_fe["is_weekend"] = (
    smart_fe["day_of_week"] >= 5
).astype(int)

In [67]:
print("\nSmart Logistics is_weekend:")
print(
    smart_fe["is_weekend"]
    .value_counts()
    .sort_index()
)

Smart Logistics is_weekend:
is_weekend
0    733
1    267
Name: count, dtype: int64

In [68]:
print(
    "Smart Logistics valid is_weekend:",
    smart_fe["is_weekend"]
    .isin([0, 1])
    .all()
)

Smart Logistics valid is_weekend: True

In [69]:
##check our logic is correct or not 
print(
    pd.crosstab(
        smart_fe["day_of_week"],
        smart_fe["is_weekend"]
    )
)

is_weekend     0    1
day_of_week
0            153    0
1            140    0
2            158    0
3            135    0
4            147    0
5              0  139
6              0  128

In [70]:
print("Smart Logistics time features:")
print(
    smart_fe[
        [
            "timestamp",
            "hour",
            "day_of_week",
            "month",
            "is_weekend"
        ]
    ].head(10)
)

print("\nSmart Logistics validation:")

print(
    "Hour valid:",
    smart_fe["hour"].between(0, 23).all()
)

print(
    "Day of week valid:",
    smart_fe["day_of_week"].between(0, 6).all()
)

print(
    "Month valid:",
    smart_fe["month"].between(1, 12).all()
)

print(
    "Weekend flag valid:",
    smart_fe["is_weekend"].isin([0, 1]).all()
)

Smart Logistics time features:
            timestamp  hour  day_of_week  month  is_weekend
0 2024-03-20 00:11:14     0            2      3           0
1 2024-10-30 07:53:51     7            2     10           0
2 2024-07-29 18:42:48    18            0      7           0
3 2024-10-28 00:50:54     0            0     10           0
4 2024-09-27 15:52:58    15            4      9           0
5 2024-09-17 06:02:15     6            1      9           0
6 2024-02-05 08:38:56     8            0      2           0
7 2024-09-28 09:08:23     9            5      9           1
8 2024-01-18 08:27:04     8            3      1           0
9 2024-11-09 00:48:26     0            5     11           1

Smart Logistics validation:
Hour valid: True
Day of week valid: True
Month valid: True
Weekend flag valid: True

======================================================Operational Features=====================================================================
see i am just evaluating the columns and checking the things whether these columns are useful for creating new features

In [82]:
print("=== Operational Feature Data Types ===")

print(
    smart_fe[
        [
            "temperature",
            "humidity",
            "traffic_status",
            "waiting_time",
            "asset_utilization",
            "inventory_level",
            "demand_forecast"
        ]
    ].dtypes
)

print("\n=== Missing Values ===")

print(
    smart_fe[
        [
            "temperature",
            "humidity",
            "traffic_status",
            "waiting_time",
            "asset_utilization",
            "inventory_level",
            "demand_forecast"
        ]
    ].isna().sum()
)

print("\n=== Numerical Feature Statistics ===")

print(
    smart_fe[
        [
            "temperature",
            "humidity",
            "waiting_time",
            "asset_utilization",
            "inventory_level",
            "demand_forecast"
        ]
    ].describe()
)

print("\n=== Operational Feature Samples ===")

print(
    smart_fe[
        [
            "temperature",
            "humidity",
            "traffic_status",
            "waiting_time",
            "asset_utilization",
            "inventory_level",
            "demand_forecast"
        ]
    ].head(20)
)

print("\n=== Traffic Status ===")

print(
    smart_fe["traffic_status"]
    .value_counts(dropna=False)
)

print("\n=== Negative Value Checks ===")

for col in [
    "temperature",
    "humidity",
    "waiting_time",
    "asset_utilization",
    "inventory_level",
    "demand_forecast"
]:
    print(
        f"{col}:",
        (smart_fe[col] < 0).sum()
    )


print("\nAsset Utilization Range:")

print(
    "Minimum:",
    smart_fe["asset_utilization"].min()
)

print(
    "Maximum:",
    smart_fe["asset_utilization"].max()
)

print("\nHumidity Range:")

print("Minimum:",smart_fe["humidity"].min())
print("Maximum:",smart_fe["humidity"].max())


print("\nWaiting Time Range:")
print(
    "Minimum:",
    smart_fe["waiting_time"].min()
)

print(
    "Maximum:",
    smart_fe["waiting_time"].max()
)

=== Operational Feature Data Types ===
temperature          float64
humidity             float64
traffic_status           str
waiting_time           int64
asset_utilization    float64
inventory_level        int64
demand_forecast        int64
dtype: object

=== Missing Values ===
temperature          0
humidity             0
traffic_status       0
waiting_time         0
asset_utilization    0
inventory_level      0
demand_forecast      0
dtype: int64

=== Numerical Feature Statistics ===
       temperature     humidity  waiting_time  asset_utilization  \
count  1000.000000  1000.000000   1000.000000        1000.000000
mean     23.893900    65.042200     35.062000          79.599100
std       3.322178     8.753765     14.477768          11.631153
min      18.000000    50.000000     10.000000          60.000000
25%      21.200000    57.200000     23.000000          69.475000
50%      23.800000    65.200000     35.000000          79.250000
75%      26.600000    72.400000     49.000000          89.425000
max      30.000000    80.000000     60.000000         100.000000

       inventory_level  demand_forecast
count      1000.000000      1000.000000
mean        297.915000       199.284000
std         113.554773        59.920847
min         100.000000       100.000000
25%         201.000000       144.000000
50%         299.000000       202.000000
75%         399.000000       251.250000
max         500.000000       300.000000

=== Operational Feature Samples ===
    temperature  humidity traffic_status  waiting_time  asset_utilization  \
0          27.0      67.8         Detour            38               60.1
1          22.5      54.3          Heavy            16               80.9
2          25.2      62.2         Detour            34               99.2
3          25.4      52.3          Heavy            37               97.4
4          20.5      57.2          Clear            56               71.6
5          24.3      61.8          Clear            56               66.8
6          20.7      75.4          Clear            32               73.3
7          23.3      64.2         Detour            30               73.8
8          26.4      77.2          Clear            14               69.6
9          21.9      57.3          Clear            52               63.1
10         22.0      53.5          Clear            28               69.8
11         29.7      63.6         Detour            13               85.5
12         21.5      74.2         Detour            38               84.4
13         27.3      71.6         Detour            30               96.4
14         25.1      76.8          Heavy            54               93.2
15         23.7      68.1          Clear            45               84.1
16         21.6      72.5          Clear            58               61.5
17         21.4      53.5         Detour            23               93.4
18         27.5      66.6         Detour            29               72.6
19         25.5      75.9          Clear            21               83.4

    inventory_level  demand_forecast
0               390              285
1               491              174
2               190              260
3               330              160
4               480              270
5               118              189
6               480              198
7               222              253
8               245              206
9               389              224
10              319              171
11              234              238
12              154              114
13              348              115
14              163              231
15              130              256
16              391              170
17              344              106
18              409              204
19              457              248

=== Traffic Status ===
traffic_status
Detour    345
Clear     328
Heavy     327
Name: count, dtype: int64

=== Negative Value Checks ===
temperature: 0
humidity: 0
waiting_time: 0
asset_utilization: 0
inventory_level: 0
demand_forecast: 0

Asset Utilization Range:
Minimum: 60.0
Maximum: 100.0

Humidity Range:
Minimum: 50.0
Maximum: 80.0

Waiting Time Range:
Minimum: 10
Maximum: 60

In [84]:
print("=== Operational Features vs Logistics Delay ===")

print(
    smart_fe.groupby("logistics_delay")[
        [
            "temperature",
            "humidity",
            "waiting_time",
            "asset_utilization",
            "inventory_level",
            "demand_forecast"
        ]
    ].mean()
)

print("\n=== Traffic Status vs Logistics Delay ===")

print(
    pd.crosstab(
        smart_fe["traffic_status"],
        smart_fe["logistics_delay"]
    )
)

=== Operational Features vs Logistics Delay ===
                 temperature   humidity  waiting_time  asset_utilization  \
logistics_delay
0                  24.038249  65.047235     36.103687          79.640783
1                  23.783216  65.038339     34.263251          79.567138

                 inventory_level  demand_forecast
logistics_delay
0                     298.347926       200.557604
1                     297.583039       198.307420

=== Traffic Status vs Logistics Delay ===
logistics_delay    0    1
traffic_status
Clear            213  115
Detour           221  124
Heavy              0  327

In [89]:
traffic_delay_rate = (
    smart_fe.groupby("traffic_status")["logistics_delay"]
    .mean()
    * 100
)

print("=== Traffic Delay Rate ===")
print(traffic_delay_rate)


print("\n\n\n")
heavy_delay_check = smart_fe[
    smart_fe["traffic_status"] == "Heavy"
]["logistics_delay"]

print("Heavy traffic records:")
print(heavy_delay_check.value_counts())

print(
    "\nAll Heavy records delayed:",
    (heavy_delay_check == 1).all()
)

=== Traffic Delay Rate ===
traffic_status
Clear      35.060976
Detour     35.942029
Heavy     100.000000
Name: logistics_delay, dtype: float64




Heavy traffic records:
logistics_delay
1    327
Name: count, dtype: int64

All Heavy records delayed: True

In [90]:
print("=== Numerical Features vs Logistics Delay Correlation ===")

numerical_operational_features = [
    "temperature",
    "humidity",
    "waiting_time",
    "asset_utilization",
    "inventory_level",
    "demand_forecast"
]

print(
    smart_fe[
        numerical_operational_features + ["logistics_delay"]
    ].corr()["logistics_delay"]
    .sort_values(ascending=False)
)

=== Numerical Features vs Logistics Delay Correlation ===
logistics_delay      1.000000
humidity            -0.000504
asset_utilization   -0.003140
inventory_level     -0.003340
demand_forecast     -0.018621
temperature         -0.038067
waiting_time        -0.063036
Name: logistics_delay, dtype: float64

===================================================ML Candidates Features===================================================================

In [91]:
smart_ml_candidates = [
    "temperature",
    "humidity",
    "traffic_status",
    "waiting_time",
    "asset_utilization",
    "inventory_level",
    "demand_forecast"
]

print("Smart Logistics ML candidate features:")
print(smart_ml_candidates)

Smart Logistics ML candidate features:
['temperature', 'humidity', 'traffic_status', 'waiting_time', 'asset_utilization', 'inventory_level', 'demand_forecast']

In [92]:
smart_simulation_features = [
    "temperature",
    "humidity",
    "traffic_status",
    "waiting_time",
    "asset_utilization",
    "inventory_level",
    "demand_forecast"
]

print("\nSmart Logistics simulation features:")
print(smart_simulation_features)

Smart Logistics simulation features:
['temperature', 'humidity', 'traffic_status', 'waiting_time', 'asset_utilization', 'inventory_level', 'demand_forecast']

In [93]:
missing_ml_features = [
    col
    for col in smart_ml_candidates
    if col not in smart_fe.columns
]

missing_simulation_features = [
    col
    for col in smart_simulation_features
    if col not in smart_fe.columns
]

print("Missing ML features:")
print(missing_ml_features)

print("\nMissing simulation features:")
print(missing_simulation_features)

Missing ML features:
[]

Missing simulation features:
[]

====================Location Feautres evaluation===============Validate Smart Logistics Coordinates============================
see i am just evaluating the columns and checking the things whether these columns are useful for creating new features

In [99]:
print("\n=== Smart Logistics Location Data Types ===")

print(
    smart_fe[
        [
            "latitude",
            "longitude",
            "asset_id"
        ]
    ].dtypes
)
print("\n=== Smart Logistics Location Missing Values ===")

print(
    smart_fe[
        [
            "latitude",
            "longitude",
            "asset_id"
        ]
    ].isna().sum()
)
print("\n=== Smart Logistics Coordinate Statistics ===")

print(
    smart_fe[
        [
            "latitude",
            "longitude"
        ]
    ].describe()
)


print("\n=== Smart Logistics Coordinate Validation ===")

print(
    "Invalid latitude:",
    (
        (smart_fe["latitude"] < -90) |
        (smart_fe["latitude"] > 90)
    ).sum()
)

print(
    "Invalid longitude:",
    (
        (smart_fe["longitude"] < -180) |
        (smart_fe["longitude"] > 180)
    ).sum()
)

print("\n=== Asset ID Analysis ===")

print(
    "Unique assets:",
    smart_fe["asset_id"].nunique()
)

print("\nAsset frequency:")
print(
    smart_fe["asset_id"]
    .value_counts()
)

=== Smart Logistics Location Data Types ===
latitude     float64
longitude    float64
asset_id         str
dtype: object

=== Smart Logistics Location Missing Values ===
latitude     0
longitude    0
asset_id     0
dtype: int64

=== Smart Logistics Coordinate Statistics ===
          latitude    longitude
count  1000.000000  1000.000000
mean     -1.360093     0.837049
std      51.997183   104.843618
min     -89.791500  -179.820200
25%     -46.167975   -88.448075
50%      -4.503150     0.678300
75%      44.502800    88.156450
max      89.870100   179.923700

=== Smart Logistics Coordinate Validation ===
Invalid latitude: 0
Invalid longitude: 0

=== Asset ID Analysis ===
Unique assets: 10

Asset frequency:
asset_id
Truck_8     109
Truck_4     107
Truck_10    105
Truck_2     105
Truck_6     103
Truck_7     102
Truck_9      94
Truck_3      93
Truck_5      93
Truck_1      89
Name: count, dtype: int64

In [102]:
smart_location_features = [
    "latitude",
    "longitude",
    "asset_id"
]

print("\nSmart Logistics location features:")
print(smart_location_features)

Smart Logistics location features:
['latitude', 'longitude', 'asset_id']

In [103]:
missing_smart_location = [
    col
    for col in smart_location_features
    if col not in smart_fe.columns
]

print("\nMissing Smart Logistics location features:")
print(missing_smart_location)

Missing Smart Logistics location features:
[]

=============================================Simulation Features====================================================

In [141]:
# Inspect Smart Logistics Features
simulation_candidates = [
    "traffic_status",
    "temperature",
    "humidity",
    "waiting_time",
    "asset_utilization",
    "inventory_level",
    "demand_forecast"
]

print("Simulation candidates:")

print(simulation_candidates)

Simulation candidates:
['traffic_status', 'temperature', 'humidity', 'waiting_time', 'asset_utilization', 'inventory_level', 'demand_forecast']

In [142]:
missing_simulation_features = [
    col
    for col in simulation_candidates
    if col not in smart_fe.columns
]

print("\nMissing simulation features:")
print(missing_simulation_features)

Missing simulation features:
[]

In [143]:
# Core Simulation Features
core_simulation_features = [
    "traffic_status",
    "temperature",
    "humidity",
    "waiting_time",
    "asset_utilization"
]

print("Core simulation features:")

print(core_simulation_features)

Core simulation features:
['traffic_status', 'temperature', 'humidity', 'waiting_time', 'asset_utilization']

In [144]:
print("\nMissing core simulation features:")

print([
    col
    for col in core_simulation_features
    if col not in smart_fe.columns
])

Missing core simulation features:
[]

In [162]:
print("\nSmart Logistics final feature-engineered shape:")
print(smart_fe.shape)

print("\nSmart Logistics columns:")
print(smart_fe.columns.tolist())

Smart Logistics final feature-engineered shape:
(1000, 20)

Smart Logistics columns:
['timestamp', 'asset_id', 'latitude', 'longitude', 'inventory_level', 'shipment_status', 'temperature', 'humidity', 'traffic_status', 'waiting_time', 'user_transaction_amount', 'user_purchase_frequency', 'logistics_delay_reason', 'asset_utilization', 'demand_forecast', 'logistics_delay', 'hour', 'day_of_week', 'month', 'is_weekend']

In [163]:
print("\n=== Smart Logistics Missing Values ===")

print(
    smart_fe.isna().sum()[
        smart_fe.isna().sum() > 0
    ]
)

=== Smart Logistics Missing Values ===
logistics_delay_reason    263
dtype: int64

In [166]:
print(
    "Smart Logistics duplicate rows:",
    smart_fe.duplicated().sum()
)

Smart Logistics duplicate rows: 0

""""""""""""""""""""""""""""""""""""""""""""""Save the final Processed Dataset

In [169]:
smart_fe.to_csv(
    "../datasets/processed/smart_logistics_features.csv",
    index=False
)

In [170]:
print(
    os.path.exists(
        "../datasets/processed/smart_logistics_features.csv"
    )
)

True